# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=alaurans/scipy-notebook
FROM $BASE_CONTAINER

# Install Torch
RUN pip install --quiet --no-cache torch
